# Generated by Django 2.2.8 on 2021-08-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=500, unique=True, verbose_name='Наименование хранилища')),
                ('cells_columns_count', models.IntegerField(verbose_name='Количество полок')),
                ('cells_rows_count', models.IntegerField(verbose_name='Количество сейфов в ряду')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=500, verbose_name='Название документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Когда обновлен')),
                ('cell_row', models.IntegerField(verbose_name='Номер полки')),
                ('cell_column', models.IntegerField(verbose_name='Номер сейфа')),
                ('number', models.IntegerField(verbose_name='Количество экземпляров')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Storage', verbose_name='Хранилище')),
            ],
        ),
        migrations.CreateModel(
            name='DocsInUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_use', models.CharField(max_length=500, verbose_name='Кто взял')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда взял')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document', verbose_name='Документ')),
            ],
        ),
    ]
