# Generated by Django 2.2.8 on 2021-08-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='number',
        ),
        migrations.AlterField(
            model_name='docsinuse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docsinuse',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document'),
        ),
        migrations.AlterField(
            model_name='docsinuse',
            name='who_use',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='cell_column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='cell_row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Storage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cells_columns_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cells_rows_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='DocsInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document')),
            ],
        ),
    ]
