# Generated by Django 2.2.8 on 2021-08-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210825_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsinuse',
            name='document',
        ),
        migrations.AddField(
            model_name='docsinuse',
            name='doc_instance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.DocsInstance'),
        ),
    ]
