# Generated by Django 2.2.8 on 2021-08-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210825_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Storage'),
        ),
    ]
