# Generated by Django 2.2.8 on 2021-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='doc_instance_unique_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='who_use',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
